# ELABORE UM PROGRAMA QUE CALCULE O VALOR A SER PAGO POR UM PRODUTO, CONSIDERANDO O SEU PREÇO NORMAL E CONDIÇÃO DE PAGAMENTO:
# A VISTA DINHEIRO/CHEQUE: 10% DE DESCONTO
# A VISTA NO CARTAO: 5% DE DESCONTO
# EM ATE 2X NO CARTAO: PREÇO NORMAL
# 3X OU MAIS NO CARTAO: 20% JUROS