# ESCREVA UMA LOGICA QUE LEIA O PESO E A ALTURA DE UMA PESSOA, CALCULE O IMC E MOSTRE SEU STATUS, DE ACORDO COM A TABELA
# ABAIXO DE 18.5: ABAIXO DO PESO 
# ENTRE 18.5 E 25: PESO IDEAL
# 25 ATE 30: SOBREPESO
# 30 A 40: OBESIDADE
# ACIMA DE 40: OBESIDADE MORBIDA