#  REFAÇA O DESAFIO 034 DOS TRIANGULOS ACRESCENTANDO O RECURSO DE MOSTRAR QUE TIPO DE TRIANGULO SERA FORMADO:
# EQUILATERO: TODOS OS LADOS IGUAIS
# ISOSCELES: DOIS LADOS IGUAIS
# ESCALENO: TODOS OS LADOS DIFERENTES