# ESCREVA UM PROGRAMA PARA APROVAR UM EMPRESTIMO BANCARIO PARA A OMPRA DE UMA CASA. O PROGRAMA VAI PERGUNTAR O VALOR DA CASA, O SALARIO DO COMPRADOR E EM QUANTOS ANOS ELE VAI PAGAR.
# CALUCULE O VALOR DA PRESTAÇÃO MENSAL SABENDO QUE ELA NAO PODE EXCEDER 30% DO SALARIO OU ENTAO O EMPRESTIMO SER NEGADO

