# CRIE UM PROGRAMA QUE LEIA DUAS NOTAS E CALUCLE A MEDIA DO ALUNO, MOSTRANDO UMA MENSAGEM NO FINAL DE ACORDO COM A MEDIA
# MEDIA ABAIXO DE 5.0: REPROVADO
# MEDIA ENTRE 4.0 E 6.9: RECUPERAÇÃO
# MEDIA 7.0 OU SUPERIOR: APROVADO
