# FAÇA UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO E INFORME, DE ACORDO COM SUA IDADE...
# SE ELE AINDA VAI SE ALISTAR AO SERVIÇO., SE E A HORA DE SE ALISTAR OU SE JA PASSOU DO TEMPO DO ALISTAMENTO
# O PROGRAMA TAMBEM DEVERA MOSTAR O TEMPO QUE FALTA OU QUE PASSOU DO PRAZO

